dataSetPath = './dataSet/dataSet.csv'
random_forest_path = './storage/randomForest.pkl'
knn_path = './storage/knn.pkl'
linear_svc_path = './storage/linear_svc.pkl'
bernoli_path = './storage/bernoulli_nb.pkl'
perceptron_path = './storage/multi_layer_perceptron.pkl'
